name: TerraformInfraCode  #ProjectName

on: #ye hai trigger
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: #Yahan job se hi start hota h
  Terrafom-plan: #Job ka name h
    runs-on: ubuntu-latest
    steps: 
      - name: repo checkout
        uses: actions/checkout@v5
    







        
        

